In [1]:
# Multiple Linear Regression

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
# Importing the dataset
dataset = pd.read_csv(r'C:\Users\abc\Desktop\Life Expectancy Data.csv')


# Preprocessing data:

# 1. handling missing data

In [8]:
# Taking care of missing data
from sklearn.impute import SimpleImputer #sklearn is library


In [9]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') #nan is not a number
imputer = imputer.fit(dataset.iloc[:, 3:]) # fit calculates mean 
dataset.iloc[:, 3:] = imputer.transform(dataset.iloc[:, 3:]) #transform means to apply

# 2. converting categorical data to numerical data

In [11]:
# Encoding categorical data ie converting categorical to numerical
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
dataset.iloc[:, :1] = labelencoder_X.fit_transform(dataset.iloc[:, :1]) 


C:\Users\abc\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [12]:
# Encoding categorical data ie converting categorical to numerical
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
dataset.iloc[:, 1] = labelencoder_X.fit_transform(dataset.iloc[:, 1]) 


In [13]:
# Encoding categorical data ie converting categorical to numerical
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
dataset.iloc[:, 2] = labelencoder_X.fit_transform(dataset.iloc[:, 2]) 


In [14]:
dataset.iloc[:, :1]

Country
0           0
1           0
2           0
3           0
4           0
...       ...
2933      192
2934      192
2935      192
2936      192
2937      192

[2938 rows x 1 columns]

In [15]:
dataset.iloc[:, 1]

0       15
1       14
2       13
3       12
4       11
        ..
2933     4
2934     3
2935     2
2936     1
2937     0
Name: Year, Length: 2938, dtype: int64

In [16]:
dataset.iloc[:, 2]

0       1
1       1
2       1
3       1
4       1
       ..
2933    1
2934    1
2935    1
2936    1
2937    1
Name: Status, Length: 2938, dtype: int32

# Dataset after data preprocessing:

In [17]:
dataset

Country  Year  Status  Adult Mortality  infant deaths  Alcohol  \
0           0    15       1            263.0           62.0     0.01   
1           0    14       1            271.0           64.0     0.01   
2           0    13       1            268.0           66.0     0.01   
3           0    12       1            272.0           69.0     0.01   
4           0    11       1            275.0           71.0     0.01   
...       ...   ...     ...              ...            ...      ...   
2933      192     4       1            723.0           27.0     4.36   
2934      192     3       1            715.0           26.0     4.06   
2935      192     2       1             73.0           25.0     4.43   
2936      192     1       1            686.0           25.0     1.72   
2937      192     0       1            665.0           24.0     1.68   

      percentage expenditure  Hepatitis B  Measles    BMI   ...  \
0                  71.279624         65.0    1154.0   19.1  ...   
1                  73.523582         62.0     492.0   18.6  ...   
2                  73.219243         64.0     430.0   18.1  ...   
3                  78.184215         67.0    2787.0   17.6  ...   
4                   7.097109         68.0    3013.0   17.2  ...   
...                      ...          ...       ...    ...  ...   
2933                0.000000         68.0      31.0   27.1  ...   
2934                0.000000          7.0     998.0   26.7  ...   
2935                0.000000         73.0     304.0   26.3  ...   
2936                0.000000         76.0     529.0   25.9  ...   
2937                0.000000         79.0    1483.0   25.5  ...   

      Total expenditure  Diphtheria    HIV/AIDS         GDP  Population  \
0                  8.16         65.0        0.1  584.259210  33736494.0   
1                  8.18         62.0        0.1  612.696514    327582.0   
2                  8.13         64.0        0.1  631.744976  31731688.0   
3                  8.52         67.0        0.1  669.959000   3696958.0   
4                  7.87         68.0        0.1   63.537231   2978599.0   
...                 ...          ...        ...         ...         ...   
2933               7.13         65.0       33.6  454.366654  12777511.0   
2934               6.52         68.0       36.7  453.351155  12633897.0   
2935               6.53         71.0       39.8   57.348340    125525.0   
2936               6.16         75.0       42.1  548.587312  12366165.0   
2937               7.10         78.0       43.5  547.358879  12222251.0   

       thinness  1-19 years   thinness 5-9 years  \
0                      17.2                 17.3   
1                      17.5                 17.5   
2                      17.7                 17.7   
3                      17.9                 18.0   
4                      18.2                 18.2   
...                     ...                  ...   
2933                    9.4                  9.4   
2934                    9.8                  9.9   
2935                    1.2                  1.3   
2936                    1.6                  1.7   
2937                   11.0                 11.2   

      Income composition of resources  Schooling  Life expectancy   
0                               0.479       10.1              65.0  
1                               0.476       10.0              59.9  
2                               0.470        9.9              59.9  
3                               0.463        9.8              59.5  
4                               0.454        9.5              59.2  
...                               ...        ...               ...  
2933                            0.407        9.2              44.3  
2934                            0.418        9.5              44.5  
2935                            0.427       10.0              44.8  
2936                            0.427        9.8              45.3  
2937                            0.434        9.8   

# seperating dependent and independent variables

In [18]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 21].values

In [19]:
X

array([[  0.   ,  15.   ,   1.   , ...,  17.3  ,   0.479,  10.1  ],
       [  0.   ,  14.   ,   1.   , ...,  17.5  ,   0.476,  10.   ],
       [  0.   ,  13.   ,   1.   , ...,  17.7  ,   0.47 ,   9.9  ],
       ...,
       [192.   ,   2.   ,   1.   , ...,   1.3  ,   0.427,  10.   ],
       [192.   ,   1.   ,   1.   , ...,   1.7  ,   0.427,   9.8  ],
       [192.   ,   0.   ,   1.   , ...,  11.2  ,   0.434,   9.8  ]])

In [20]:
y

array([65. , 59.9, 59.9, ..., 44.8, 45.3, 46. ])

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)


# performing multilinear regression

In [23]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)

In [26]:
y_pred

array([80.60923888, 74.15747389, 75.65456555, 79.62317163, 83.48275745,
       70.4387663 , 63.71514444, 74.72537499, 73.29745685, 71.28052457,
       55.09237812, 61.42399362, 79.71856687, 73.82178673, 61.07268323,
       72.60203538, 69.34613251, 70.34445519, 72.86866293, 75.14894241,
       69.53162183, 72.92089831, 61.82369807, 64.53501069, 68.33753364,
       71.92242949, 68.69680349, 69.70950583, 81.00033527, 81.5860778 ,
       61.45040483, 61.34935613, 57.04504858, 65.39004462, 75.4729981 ,
       84.55415092, 73.65900472, 77.12236714, 72.39063733, 81.52537754,
       69.24253059, 73.92303042, 65.03075556, 85.00786982, 52.20391776,
       73.26551636, 76.57704922, 63.5039404 , 69.24378516, 58.74702327,
       69.13962427, 70.98423276, 76.97936589, 66.84867943, 54.42224161,
       72.51970623, 82.34532234, 72.67182771, 82.59754419, 67.50662992,
       76.30879991, 70.65076766, 70.53397818, 58.74931705, 79.09849881,
       68.40179375, 73.85395249, 67.73425044, 64.88442345, 68.67

In [28]:
y_test

array([82.        , 79.2       , 78.4       , 81.1       , 88.        ,
       66.8       , 50.        , 75.4       , 74.7       , 74.3       ,
       55.        , 55.5       , 75.5       , 73.8       , 51.6       ,
       86.        , 65.4       , 73.4       , 68.5       , 74.1       ,
       71.5       , 73.7       , 62.8       , 58.1       , 58.6       ,
       67.8       , 77.7       , 72.4       , 77.3       , 79.9       ,
       71.6       , 59.9       , 55.        , 55.3       , 78.6       ,
       81.3       , 72.4       , 66.4       , 79.6       , 81.3       ,
       77.6       , 74.1       , 62.2       , 82.7       , 57.2       ,
       73.5       , 81.        , 59.4       , 69.        , 63.3       ,
       67.7       , 67.7       , 74.6       , 61.8       , 56.4       ,
       82.        , 89.        , 73.2       , 81.8       , 65.4       ,
       77.6       , 73.        , 69.        , 57.5       , 74.1       ,
       71.1       , 72.7       , 73.        , 59.7       , 73.  

In [35]:
from sklearn.metrics import mean_squared_error

In [37]:
mean_squared_error(y_test, y_pred)

17.785257613712012